bot:
  userName: "SwaggyBot"
  token: "1907533091:AAFVMX4jJTCHvON6n9x5rgH6AKuPWPg3AVU"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account_module?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=Europe/Rome&useLegacyDatetimeCode=false
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  error:
    include-message: always